export const AUTH_ERROR_CODES = {
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",

    AUTH_EMAIL_REQUIRED: "AUTH_EMAIL_REQUIRED",
    AUTH_PHONE_REQUIRED: "AUTH_PHONE_REQUIRED",
    AUTH_NAME_REQUIRED: "AUTH_NAME_REQUIRED",
    AUTH_PASSWORD_REQUIRED: "AUTH_PASSWORD_REQUIRED",

    AUTH_EMAIL_INVALID: "AUTH_EMAIL_INVALID",
    AUTH_PHONE_INVALID: "AUTH_PHONE_INVALID",
    AUTH_NAME_INVALID: "AUTH_NAME_INVALID",
    AUTH_PASSWORD_WEAK: "AUTH_PASSWORD_WEAK",

    AUTH_GOOGLE_TOKEN_INVALID: "AUTH_GOOGLE_TOKEN_INVALID",
    AUTH_GOOGLE_TOKEN_PAYLOAD_INVALID: "AUTH_GOOGLE_TOKEN_PAYLOAD_INVALID",
    AUTH_GOOGLE_EMAIL_NOT_VERIFIED: "AUTH_GOOGLE_EMAIL_NOT_VERIFIED",

    AUTH_REFRESH_TOKEN_REQUIRED: "AUTH_REFRESH_TOKEN_REQUIRED",
    AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
