export const BANNER_ERROR_CODES = {
    BANNER_NOT_FOUND: "BANNER_NOT_FOUND",
    BANNER_UPLOAD_FAILED: "BANNER_UPLOAD_FAILED",
    BANNER_FILE_TOO_LARGE: "BANNER_FILE_TOO_LARGE",
    BANNER_FILE_REQUIRED: "BANNER_FILE_REQUIRED",
} as const;

export type BannerErrorCode = (typeof BANNER_ERROR_CODES)[keyof typeof BANNER_ERROR_CODES];
