export const CATEGORY_ERROR_CODES = {
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    CATEGORY_ALREADY_EXISTS: "CATEGORY_ALREADY_EXISTS",
    INVALID_CATEGORY_ID: "INVALID_CATEGORY_ID",
    SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
    PARENT_CATEGORY_NOT_FOUND: "PARENT_CATEGORY_NOT_FOUND",
    CATEGORY_REQUIRED_FIELDS: "CATEGORY_REQUIRED_FIELDS",
} as const;

export type CategoryErrorCode = (typeof CATEGORY_ERROR_CODES)[keyof typeof CATEGORY_ERROR_CODES];
