export const CONSULTATION_ERROR_CODES = {
    CONSULTATION_NOT_FOUND: "CONSULTATION_NOT_FOUND",
    INVALID_CONSULTATION_ID: "INVALID_CONSULTATION_ID",
    INVALID_CONSULTATION_STATUS: "INVALID_CONSULTATION_STATUS",
    CONSULTATION_REQUIRED_FIELDS: "CONSULTATION_REQUIRED_FIELDS",
} as const;

export type ConsultationErrorCode =
    (typeof CONSULTATION_ERROR_CODES)[keyof typeof CONSULTATION_ERROR_CODES];
