export const COOPERATION_ERROR_CODES = {
    COOPERATION_NOT_FOUND: "COOPERATION_NOT_FOUND",
    INVALID_COOPERATION_ID: "INVALID_COOPERATION_ID",
    INVALID_COOPERATION_STATUS: "INVALID_COOPERATION_STATUS",
    COOPERATION_REQUIRED_FIELDS: "COOPERATION_REQUIRED_FIELDS",
} as const;

export type CooperationErrorCode =
    (typeof COOPERATION_ERROR_CODES)[keyof typeof COOPERATION_ERROR_CODES];
