export const PASSWORD_ERROR_CODES = {
    PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
    PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
    PASSWORD_LETTER_REQUIRED: "PASSWORD_LETTER_REQUIRED",
    PASSWORD_DIGIT_REQUIRED: "PASSWORD_DIGIT_REQUIRED",
} as const;

export type PasswordErrorCode = (typeof PASSWORD_ERROR_CODES)[keyof typeof PASSWORD_ERROR_CODES];
