export const PRODUCT_ERROR_CODES = {
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    PRODUCT_ALREADY_EXISTS: "PRODUCT_ALREADY_EXISTS",
    INVALID_PRODUCT_ID: "INVALID_PRODUCT_ID",
    INVALID_PRODUCT_VOLUME: "INVALID_PRODUCT_VOLUME",
    CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
    INVALID_QUANTITY: "INVALID_QUANTITY",
} as const;

export type ProductErrorCode = (typeof PRODUCT_ERROR_CODES)[keyof typeof PRODUCT_ERROR_CODES];
