export const NAV_PAGE_LABELS = {
    "/": "Головна",
    "/catalog": "Каталог",
    "/search": "Пошук",
    "/cart": "Кошик",
    "/wishlist": "Обране",
    "/checkout": "Оформлення замовлення",
    "/checkout/success": "Замовлення оформлено",
    "/order-tracking": "Відстеження замовлення",
    "/about": "Про компанію",
    "/contacts": "Контакти",
    "/consultation": "Консультація",
    "/cooperation": "Співпраця",
    "/delivery-payment": "Доставка і оплата",
    "/faq": "Поширені питання",
    "/privacy-policy": "Політика конфіденційності",
    "/public-offer": "Публічна оферта",
    "/return-exchange": "Обмін та повернення",
    "/login": "Вхід",
    "/register": "Реєстрація",
    "/forgot-password": "Відновлення пароля",
    "/reset-password": "Скидання пароля",
    "/403": "Доступ заборонено",
    "/account": "Особистий кабінет",
    "/account/profile": "Профіль",
    "/account/orders": "Мої замовлення",
    "/account/addresses": "Мої адреси",
    "/account/change-password": "Зміна пароля",
    "/admin": "Адмін-панель",
    "/admin/products": "Товари",
    "/admin/categories": "Категорії",
    "/admin/orders": "Замовлення",
    "/admin/users": "Користувачі",
    "/admin/reviews": "Відгуки",
    "/admin/banners": "Банери",
    "/admin/analytics": "Аналітика",
    "/error": "Помилка",
    "/500": "Помилка сервера",
    "/404": "Сторінку не знайдено",
    "/maintenance": "Технічні роботи",
} as const;
