import type { Slug } from "@shared/primitives";

export const ROUTES = {
    HOME: "/",
    CATALOG: "/catalog",
    CATALOG_ROUTE: "/catalog/:slug",
    CATEGORY: (slug: Slug) => `/catalog/${slug}`,
    PRODUCTS: "/products",
    PRODUCT_ROUTE: "/products/:slug",
    PRODUCT: (slug: Slug) => `/products/${slug}`,
    SEARCH: "/search",
    CART: "/cart",
    WISHLIST: "/wishlist",
    CHECKOUT: "/checkout",
    CHECKOUT_SUCCESS: "/checkout/success",
    ORDER_TRACKING: "/order-tracking",
    ABOUT: "/about",
    CONTACTS: "/contacts",
    CONSULTATION: "/consultation",
    COOPERATION: "/cooperation",
    DELIVERY_PAYMENT: "/delivery-payment",
    FAQ: "/faq",
    PRIVACY_POLICY: "/privacy-policy",
    PUBLIC_OFFER: "/public-offer",
    RETURN_EXCHANGE: "/return-exchange",
    LOGIN: "/login",
    REGISTER: "/register",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    UNAUTHORIZED: "/403",
    ACCOUNT: "/account",
    ACCOUNT_DASHBOARD: "/account",
    ACCOUNT_PROFILE: "/account/profile",
    ACCOUNT_ORDERS: "/account/orders",
    ACCOUNT_ORDER_DETAILS_ROUTE: "/account/orders/:orderId",
    ACCOUNT_ORDER_DETAILS: (orderId: string) => `/account/orders/${orderId}`,
    ACCOUNT_ADDRESSES: "/account/addresses",
    ACCOUNT_CHANGE_PASSWORD: "/account/change-password",
    ADMIN: "/admin",
    ADMIN_DASHBOARD: "/admin",
    ADMIN_PRODUCTS: "/admin/products",
    ADMIN_PRODUCT_EDIT_ROUTE: "/admin/products/:productId",
    ADMIN_PRODUCT_EDIT: (productId: string) => `/admin/products/${productId}`,
    ADMIN_CATEGORIES: "/admin/categories",
    ADMIN_ORDERS: "/admin/orders",
    ADMIN_ORDER_DETAILS_ROUTE: "/admin/orders/:orderId",
    ADMIN_ORDER_DETAILS: (orderId: string) => `/admin/orders/${orderId}`,
    ADMIN_USERS: "/admin/users",
    ADMIN_REVIEWS: "/admin/reviews",
    ADMIN_BANNERS: "/admin/banners",
    ADMIN_ANALYTICS: "/admin/analytics",
    ERROR: "/error",
    SERVER_ERROR: "/500",
    NOT_FOUND: "/404",
    MAINTENANCE: "/maintenance",
} as const;
